feat: Bill No and Bill Date in Purchase Details Report
ParaLogicTech/erpnext pull request #115
Opened 2022-09-28 11:41 UTC by haiderk0987

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2022-09-28 13:33 UTC, SaiFi0102 requested changes

2022-09-28 13:33 UTC, SaiFi0102 commented on erpnext/selling/report/sales_details/sales_details.py
> +				columns += [bill_no_field, bill_date_field]
Add only Bill No column

2022-09-28 13:33 UTC, SaiFi0102 commented on erpnext/selling/report/sales_details/sales_details.py
> +				columns += [bill_date_field, bill_date_field]
Add only Bill Date column

2022-09-29 13:11 UTC, haiderk0987 commented
Change completed

2022-10-01 11:30 UTC, merged