feat(Workshop CP): Add Tasks Status in Project
ParaLogicTech/erpnext pull request #249
Opened 2023-08-23 13:26 UTC by Murtazaabidi1

Closes: https://github.com/ParaLogicTech/erpnext/issues/236

2023-08-24 06:39 UTC, SaiFi0102 requested changes

2023-08-24 06:39 UTC, SaiFi0102 commented on erpnext/projects/doctype/task/task.json
> +   "options": "Open\nWorking\nPending Review\nOn Hold\nOverdue\nCompleted\nCancelled"
Lets remove Overdue Status options, and instead add an "Overdue" checkbox field. Update background worker method for setting overdue, check all references where Overdue status is being set or used. Add patch to set status for Overdue to Working tasks if any

2023-08-24 06:39 UTC, SaiFi0102 commented on erpnext/projects/doctype/task/task.json
>     "oldfieldtype": "Select",
Lets add a database index to this status field

2023-08-24 06:39 UTC, SaiFi0102 commented on erpnext/projects/doctype/project/project.py
> +				self.tasks_status = "Not Started"
These conditions should have an else block to handle any future cases. The "In Progress" part should be in the else block and everything else should have an explicit condition

2023-08-24 06:39 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.py
> +	# "tasks_status",
Uncomment this ... now the field is allowed for sorting/filtering. Also update task status filter options

2023-08-24 08:01 UTC, SaiFi0102 commented on erpnext/projects/doctype/project/project.py
> +				self.tasks_status = "Not Started"
CHeck for Working and Pending review both in On Hold condition

2023-08-24 08:06 UTC, SaiFi0102 commented on erpnext/projects/doctype/task/task.json
> +   "options": "Open\nWorking\nPending Review\nOn Hold\nOverdue\nCompleted\nCancelled"
- Read only, no copy checkbox `is_overdue`
- Change `Task.update_status()` to `Task.set_is_overdue(update=False, update_modifed=False)`
- Move all over due determination logic in the `Task.set_is_overdue()` method
- Call `Task.set_is_overdue()` in validate

2023-08-24 09:57 UTC, SaiFi0102 requested changes

2023-08-24 09:57 UTC, SaiFi0102 commented on erpnext/projects/doctype/project/project.py
> +			elif any(d.status in ["On Hold", "Pending Review"]  for d in tasks_data) and all(d.status != "Working" for d in tasks_data):
WRong condition, read again

2023-08-24 09:57 UTC, SaiFi0102 commented on erpnext/projects/doctype/task/task.py
> +	def set_is_overdue(self):
- Should be a setter, update db only if argument provided
- Logic should be based on default 0
- Should only affect is_overdue, no need to call `update_project` or `notify_update`

2023-08-24 09:57 UTC, SaiFi0102 commented on erpnext/projects/doctype/task/task.py
> +		doc.set_is_overdue(update=False, update_modifed=False)
`update=True`

2023-08-24 09:57 UTC, SaiFi0102 commented on erpnext/projects/doctype/task/task.py
> +	tasks = frappe.get_all("Task", filters={"status": ["not in", ["Cancelled", "Completed"]]})
filter by `exp_end_date < today`

2023-08-25 12:18 UTC, SaiFi0102 requested changes

2023-08-25 12:18 UTC, SaiFi0102 commented on erpnext/projects/doctype/task/task.py
> +		"exp_end_date": ["<", today],
Test your code first

2023-08-25 12:18 UTC, SaiFi0102 commented on erpnext/projects/doctype/task/task.py
> +	def set_is_overdue(self, update=False):
`update_modified` should be an argument. Also write a patch for tasks that had `status == "Overdue"`. Set `status = "Working"` and `is_overdue = 1`

2023-08-25 12:18 UTC, SaiFi0102 commented on erpnext/projects/doctype/task/task.py
> +			self.is_overdue = cint(self.exp_end_date and getdate(self.exp_end_date) < getdate())
Still not good enough

2023-09-04 11:44 UTC, haiderk0987 commented on erpnext/projects/doctype/task/task.json
> +   "fieldname": "project_template",
read_only and no_copy

2023-09-04 11:44 UTC, haiderk0987 commented on erpnext/projects/doctype/task/task.json
> +   "fieldname": "project_template_detail",
read_only and no_copy

2023-09-04 11:48 UTC, haiderk0987 commented on erpnext/patches/v14_0/set_project_tasks_status.py
> +	frappe.reload_doc("projects", "doctype", "tasks_status")
frappe.reload_doc("projects", "doctype", "project") or
frappe.reload_doc("Projects", "doctype", "Project")

Both will work

2023-09-04 11:49 UTC, haiderk0987 commented on erpnext/patches.txt
> +erpnext.patches.v14_0.set_task_is_overdue #1 #2
forgot to call set_project_tasks_status in patches.txt

2023-09-04 11:52 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/templates/workshop_cp_dashboard.html
>  <div class="row form-section card-section visible-section" role="tabpanel">
this file was not supposed to be included in this PR.

2023-09-04 11:53 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/templates/workshop_cp_vehicle_row.html
this file was not supposed to be included in this PR.

2023-09-04 11:53 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
>  					{ fieldname: 'vehicle_received_date', label: __('Vehicle Received Date') },
this file was not supposed to be included in this PR.

2023-09-04 12:38 UTC, haiderk0987 commented on erpnext/projects/doctype/project/project.py
> +		incomplete_task = frappe.db.get_value("Task", {'project':self.name, 'status': ['!=', 'Completed']})
check if validate_task_completed is checked in Project Settings

2023-09-04 12:38 UTC, haiderk0987 commented on erpnext/projects/doctype/project/project.py
> +			elif any(d.status == "On Hold" for d in tasks_data) and all(d.status != ["Working", "Pending Review"] for d in tasks_data):
d.status in ["Working", "Pending Review"]

2023-09-04 12:38 UTC, haiderk0987 commented on erpnext/projects/doctype/task/task.py
> +			""".format(d[0], d[1]), cstr(task_list[count]))
add the tab back

2023-09-04 12:38 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/templates/workshop_cp_vehicle_row.html
> +					{% if doc.completed_tasks == doc.total_tasks %}
if doc.total_tasks && doc.completed_tasks == doc.total_tasks

2023-09-04 12:38 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.py
> +		task_doc = frappe.new_doc("Task")
unindent it by one level

2023-09-12 07:01 UTC, SaiFi0102 requested changes

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/projects/doctype/project/project.json
> +   "options": "\nNo Tasks\nNot Started\nIn Progress\nOn Hold\nCompleted",
No empty status option

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/projects/doctype/project/project.py
> +	def validate_task_complete(self):
should be plural

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/projects/doctype/project/project.py
> +			frappe.throw(_("{0} not completed: ").format(frappe.get_desk_link("Task", incomplete_task)))
What is this colon for?

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/projects/doctype/projects_settings/projects_settings.json
> +   "label": "Validate Task Completed for Ready To Close"
Should be plural

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/templates/workshop_cp_vehicle_row.html
> +				{% endif %}
Should use button rather than `<a>`

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
> +				title: __('Create task'),
Task should be Title Case

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
> +		frappe.call({
async function should return promise!

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
> +		frappe.call({
async function should return promise!

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
> +	async create_task(e) {
async function should return promise!

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.py
> +def create_template_task(project):
should be plural!

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.py
> +	task_doc.notify_update()
`doc.save()` already does notify update. no need to manually call `notify_update()`

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.py
> +def create_custom_task(subject, project, standard_time):
`standard_time` not being used

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.py
> +	doc.notify_update()
we already have an API for this .. no need to duplicate the API

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.py
> +	frappe.msgprint(_("Task for {0} created".format(task_doc.subject)))
Bad english

2023-09-12 07:01 UTC, SaiFi0102 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.py
> +	doc.notify_update()
We already have an API for this .. no need to duplicate the API

2023-09-21 09:53 UTC, SaiFi0102 approved these changes

2023-09-21 09:53 UTC, merged