Vehicle Number Plate handling
ParaLogicTech/erpnext pull request #252
Opened 2023-09-06 07:27 UTC by haiderk0987

2023-09-08 12:20 UTC, SaiFi0102 requested changes

2023-09-08 12:20 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_number_plate_delivery/vehicle_number_plate_delivery.json
> + "permissions": [
Update permissions ... similar to vehicle invoice delivery

2023-09-08 12:20 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_number_plate_delivery/vehicle_number_plate_delivery.json
> +   "read_only": 1
Don't need this field .. we only need this field for stock related documents

2023-09-08 12:20 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_number_plate_delivery/vehicle_number_plate_delivery.py
> +			"vehicle_license_plate": self.vehicle_license_plate,
No need specify reg # in filter .. One Vehicle one Number Plate delivery would be fine

2023-09-08 12:20 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_number_plate_delivery/vehicle_number_plate_delivery.py
> +
indentation is not good

2023-09-08 12:20 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_number_plate_receipt/vehicle_number_plate_receipt.json
> + "permissions": [
Set permissions similar to Vehicle Invoice (Receipt)

2023-09-08 12:20 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_number_plate_receipt/vehicle_number_plate_receipt.py
> +				"vehicle_license_plate": d.vehicle_license_plate,
no need to specify reg # .. one vehicle one number plate receipt is fine

2023-09-08 12:20 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_number_plate_receipt/vehicle_number_plate_receipt.py
> +				"name": ['!=', d.name]
`parent != self.name`

2023-09-08 12:20 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_number_plate_receipt/vehicle_number_plate_receipt.json
> +  "amended_from"
Amended from in the first section bottom right

2023-09-08 12:20 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_registration_order/vehicle_registration_order.py
> +	def set_number_plate_status(self, update=False):
argument `update_modified=True`

2023-09-10 18:09 UTC, haiderk0987 commented on erpnext/vehicles/doctype/vehicle_number_plate_delivery/vehicle_number_plate_delivery.py
> +			"vehicle_license_plate": self.vehicle_license_plate,
Ain't there a possibility for another reg #?

2023-09-10 18:09 UTC, haiderk0987 commented on erpnext/vehicles/doctype/vehicle_number_plate_delivery/vehicle_number_plate_delivery.py
> +
...

2023-09-11 18:09 UTC, SaiFi0102 approved these changes

2023-09-11 18:09 UTC, merged

2023-09-11 19:38 UTC, SaiFi0102 commented
https://github.com/ParaLogicTech/erpnext/commit/9e0f00ce46b3cb9683db2ee88887a4fc0cbe7924