feat(Workshop CP): Create Task Tab
ParaLogicTech/erpnext pull request #259
Opened 2023-09-21 14:00 UTC by Murtazaabidi1

2023-10-03 13:19 UTC, haiderk0987 requested changes

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/projects/doctype/task/task.py
> +		if self.status not in ['Open', 'Cancelled'] and not self.assigned_to:
what about 'overdue' status?

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/templates/workshop_cp_tasks.html
> +	<div class="section-body">
Does this div serve any purpose?

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
> +		$(this.parent).on("click", ".unassigned_technician", (e) => this.reassign_technician(e));
why different tags here? Decide a single term instead of 2 different terms; unassigned_technician and reassign_technician

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/templates/workshop_cp_task_row.html
> +				<button class="dropdown-item  delete_task" data-task="{{doc.name}}">{{ __("Delete Task") }}</button>
Delete should be at the end. And with red color text, I guess?

How about 3 sections in the dropdown.
1st section => Start Task, Pause Task, Resume Task, Complete Task
2nd section => Assign Technician, Reassign Technician
3rd section => Edit Task, Delete Task

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.py
> +	task_doc.save()
No msgprint?

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.py
> +	validate_technician_available(employee, throw=True)
shift it up. after first validation

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.py
> +		ts_doc.start_date = today
remove ts_doc.start_date = today

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
> +		if (doctype == "Task"){
space betwee "){" in all condition blocks

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
> +						"read_only": 1,
why 2x read_only?

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
> +						"fieldtype": "Float",
Make standard_working_hours field read_only ?

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
> +						if (employee) {
remove conditional blocks. frappe.db.get_value will handle the nonexistent employee case

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
> +						if (employee) {
remove conditional blocks. frappe.db.get_value will handle the nonexistent employee case

2023-10-03 13:19 UTC, haiderk0987 commented on erpnext/vehicles/page/workshop_cp/workshop_cp.js
> +	async delete_task(e) {
why async modifier?

2023-10-11 10:08 UTC, SaiFi0102 commented
Will review consolidated PR

2023-10-11 10:08 UTC, merged