feat(project.js): Template task option added in repair order.
ParaLogicTech/erpnext pull request #340
Opened 2024-05-13 10:15 UTC by ebbad18

closes: https://github.com/ParaLogicTech/erpnext/issues/339

2024-05-30 06:08 UTC, ebbad18 reviewed
.

2024-05-30 06:09 UTC, ebbad18 commented on erpnext/controllers/item_variant.py
Dont pull this file, discard it.

2024-06-11 10:02 UTC, SaiFi0102 commented on erpnext/controllers/item_variant.py
Revert the file if you don't want this pulled, don't just ask for it, do it

2024-06-12 09:15 UTC, SaiFi0102 requested changes

2024-06-12 09:15 UTC, SaiFi0102 commented on erpnext/public/js/utils/projects.js
> +erpnext.projects.create_task
Remove this line

2024-06-27 07:58 UTC, closed without merging