feat(vehicle_gate_pass): Created unpaid sales invoice checkbox
ParaLogicTech/erpnext pull request #363
Opened 2024-08-09 11:35 UTC by mollyzaidi

**Feat**

Feat #345 by @Mariyaaahh

2024-08-12 12:10 UTC, SaiFi0102 requested changes

2024-08-12 12:10 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_gate_pass/vehicle_gate_pass.json
> +  "invoice_unpaid_check",
Rename field to invoice_is_unpaid ... Refactor everywhere

2024-08-12 12:10 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_gate_pass/vehicle_gate_pass.py
> +@frappe.whitelist()
remove unnecessary change

2024-08-12 12:10 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_gate_pass/vehicle_gate_pass.py
> +
remove unnecessary change

2024-08-12 12:10 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_gate_pass/vehicle_gate_pass.py
> +		self.validate_invoice_unpaid_check()
rename to `set_invoice_is_unpaid()`

2024-08-13 08:25 UTC, SaiFi0102 requested changes

2024-08-13 08:25 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_gate_pass/vehicle_gate_pass.json
> +   "fieldname": "invoice_unpaid_check",
Still not renamed

2024-08-13 08:37 UTC, mollyzaidi commented on erpnext/vehicles/doctype/vehicle_gate_pass/vehicle_gate_pass.json
> +   "fieldname": "invoice_unpaid_check",
Done

2024-08-16 08:15 UTC, SaiFi0102 requested changes

2024-08-16 08:15 UTC, SaiFi0102 commented on erpnext/vehicles/doctype/vehicle_gate_pass/vehicle_gate_pass.py
> +
Remove unnecessary new line

2024-08-16 08:48 UTC, SaiFi0102 approved these changes

2024-08-16 08:48 UTC, merged