feat: rounded payable row in accrual jv entry
ParaLogicTech/erpnext pull request #68
Opened 2021-01-29 11:48 UTC by beingeek

2021-02-03 14:05 UTC, SaiFi0102 commented on erpnext/hr/doctype/payroll_entry/payroll_entry.py
> +			ss_list = self.get_sal_slip_list(ss_status=1, as_dict=2)
Not a bug but... `as_dict=1`

2021-02-03 17:15 UTC, beingeek commented on erpnext/hr/doctype/payroll_entry/payroll_entry.py
> +			ss_list = self.get_sal_slip_list(ss_status=1, as_dict=2)
oh :p

2021-02-06 10:07 UTC, SaiFi0102 commented
Delete employee.orig file

2021-02-06 10:13 UTC, SaiFi0102 requested changes

2021-02-06 10:13 UTC, SaiFi0102 commented on erpnext/hr/doctype/payroll_entry/payroll_entry.py
> +		from `tabSalary Slip` where payroll_entry=%s and docstatus < 2 """, self.name, as_dict=1)
add conditions `ifnull(bank_name, '') != ''`

2021-02-06 10:13 UTC, SaiFi0102 commented on erpnext/hr/doctype/payroll_entry/payroll_entry.py
> +
cleanup whitespace

2021-02-06 10:13 UTC, SaiFi0102 commented on erpnext/hr/report/salary_register/salary_register.py
> +			"fieldname": "cheque_amount", "width": 120
Add keep condition.. keep if cheque amount != 0

2021-02-06 10:13 UTC, SaiFi0102 commented on erpnext/hr/report/salary_register/salary_register.py
> +			"fieldname": "cash_amount", "width": 120
Add keep condition.. keep if cash amount != 0

2021-02-06 10:13 UTC, SaiFi0102 commented on erpnext/patches/v12_0/create_banks_for_bank_name_in_employee_and_salary_slip.py
> +	bank_names = frappe.db.sql_list("SELECT DISTINCT bank_name FROM `tabEmployee` WHERE bank_name IS NOT NULL") + \
`IS NOT NULL` is not enough..
You'll also have to check for empty string
or you can combine the 2 conditions as `ifnull(bank_name, '') != ''`

2021-02-11 19:35 UTC, SaiFi0102 commented
see requested changes for patch

2021-02-11 19:54 UTC, SaiFi0102 requested changes

2021-02-11 19:54 UTC, SaiFi0102 commented on erpnext/hr/doctype/payroll_entry/payroll_entry.js
>  			method: 'erpnext.hr.doctype.payroll_entry.payroll_entry.payroll_entry_has_bank_entries',
You'll have to modify this API in order show the button even after Bank Entries exist to allow creating multiple bank entries

2021-02-11 19:54 UTC, SaiFi0102 commented on erpnext/hr/doctype/payroll_entry/payroll_entry.py
> +		enumerate(employees)
remove debug line

2021-02-11 19:54 UTC, SaiFi0102 commented on erpnext/hr/doctype/payroll_entry/payroll_entry.py
> +				if publish_progress:
move this block outside the `if emp not in salary_slips_exists_for` condition so that progress is always shown for all employees

2021-02-11 19:54 UTC, SaiFi0102 commented on erpnext/hr/doctype/salary_slip/salary_slip.js
> +		frm.add_custom_button(__('Update Salary Slip'), function () {
Make sure this button does not show after Salary Slips are submitted... add the button along with where "Submit Salary Slips" button is

2021-02-12 15:25 UTC, SaiFi0102 commented
Rebase and solve merge conflicts by using my version of `set_party_name_in_journal_entry` patch
and do your own review

2021-02-12 15:29 UTC, SaiFi0102 requested changes

2021-02-12 15:29 UTC, SaiFi0102 commented on erpnext/hr/doctype/payroll_entry/payroll_entry.py
> +		sal_slips_in_payroll = [d for d in sal_slips_in_payroll if d.bank_name]
Change condition to `d.salary_mode == 'Bank' and d.bank_name`
Make sure that salary_mode is provided with the `get_salary_slips_for_payment` method

2021-02-16 05:53 UTC, merged